---
title: "ette"
author: "Salwa Rizqina Putri"
date: "10/27/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# LOAD DATASET
```{r}
library(readxl)
dataset_uts <- read_excel("c://hp/data.xlsx")
dataset<-dataset_uts
head(dataset)
```
# LIHAT DESKRIPSI DATA
```{r}
summary(dataset)
```

# DATA PREPROCESSING
## MENGATASI MISSING VALUES
```{r}
dataset$Budget[is.na(dataset$Budget)] <- mean(dataset$Budget, na.rm = TRUE)
dataset$Screens[is.na(dataset$Screens)] <- mean(dataset$Screens, na.rm = TRUE)
dataset$AF[is.na(dataset$AF)] <- mean(dataset$AF, na.rm = TRUE)
summary(dataset)
which(is.na(dataset))
```

## UBAH TIPE DATA YANG FAKTOR
```{r}
dataset$Genre<-as.factor(dataset$Genre)
dataset$Sequel<-as.factor(dataset$Sequel)
```

## BUAT KELAS
```{r}
dataset$class<-cut(dataset$Ratings, 3, labels = c("Rendah", "Sedang", "Tinggi"))
dataset<-dataset_new
dataset$class<-as.factor(dataset$class)
summary(dataset)
```

# SPLIT DATA
```{r}
set.seed(123)
training_set <- sample(1:nrow(dataset), floor(.80 * nrow(dataset)))
testing_set <- (1:nrow(dataset))[1:nrow(dataset) %in% training_set == FALSE]
train <- dataset[training_set,]
tes <- dataset[testing_set,]
train<-train[-c(1)]
tes<-tes[-c(1)]
```

#TRAIN MODEL
```{r}
  library(nnet)          #neural network dan multiple regresi logistik
  library(rpart)         #class tree id3
  library(RWeka)         #class tree c45 dan oneR
  library(e1071)         #naive bayes
  library(randomForest)  #random forest
  svm_model <- svm  (class ~ ., data = train, 
                     kernel="radial", cost=5, probability=TRUE)
  id3_model <- rpart(class ~ ., data = train, 
                     control = rpart.control(minsplit = 2))
  c45_model <- J48  (class ~ ., data = train)
  mrl_model <- nnet::multinom(class ~., data = train)
  nn_model  <- nnet (class ~ ., data = train, size=5, decay=5e-4, 
                     maxit=200)
  rf_model  <- randomForest(class ~ ., data = train)
  nb_model  <- naiveBayes(class ~ ., data = train)
  oR_model  <- OneR(class ~ ., data = train)
```
#PREDIKSI
```{r}
#Prediksi Hasil Testing Set
  svm_pred  <- predict(svm_model, tes[,1:14])
  id3_pred  <- predict(id3_model, tes[,1:14], type = "class")
  c45_pred  <- predict(c45_model, tes[,1:14])
  mrl_pred  <- predict(mrl_model, tes[,1:14], type = "class")
  rf_pred   <- predict(rf_model , tes[,1:14])
  nb_pred   <- predict(nb_model , tes[,1:14])
  oR_pred   <- predict(oR_model , tes[,1:14], type = "class")
```

#EVALUASI
```{r}
library(mltest)
true_value<-tes$class
  CM_svm    <- ml_test(svm_pred, true_value, output.as.table = FALSE)
  CM_id3    <- ml_test(id3_pred, true_value, output.as.table = FALSE)
  CM_c45    <- ml_test(c45_pred, true_value, output.as.table = FALSE)
  CM_mrl    <- ml_test(mrl_pred, true_value, output.as.table = FALSE)
  CM_rf     <- ml_test(rf_pred , true_value, output.as.table = FALSE)
  CM_nb     <- ml_test(nb_pred , true_value, output.as.table = FALSE)
  CM_oR     <- ml_test(oR_pred , true_value, output.as.table = FALSE)
  
  Model     <- c("SVM (Support Vector Machine)","","", 
                 "Decision Tree(ID3)"          ,"","", 
                 "Algoritma C.45"              ,"","",
                 "Multinomial RegLog"          ,"","",
                 "Random Forest"               ,"","",
                 "Naive Bayes"                 ,"","",
                 "One-R"                       ,"","" )
  Akurasi   <- c(CM_svm$accuracy,"","", 
                 CM_id3$accuracy,"","", 
                 CM_c45$accuracy,"","",
                 CM_mrl$accuracy,"","",
                 CM_rf$accuracy ,"","",
                 CM_nb$accuracy ,"","",
                 CM_oR$accuracy ,"","" )
  Class     <- c("Rendah","Sedang","Tinggi",
                 "Rendah","Sedang","Tinggi",
                 "Rendah","Sedang","Tinggi",
                 "Rendah","Sedang","Tinggi",
                 "Rendah","Sedang","Tinggi",
                 "Rendah","Sedang","Tinggi",
                 "Rendah","Sedang","Tinggi")
  Presisi   <- c(CM_svm$precision, CM_id3$precision, 
                 CM_c45$precision, CM_mrl$precision,
                 CM_rf$precision , CM_nb$precision , CM_oR$precision)
  Recall    <- c(CM_svm$recall   , CM_id3$recall, 
                 CM_c45$recall   , CM_mrl$recall   ,
                 CM_rf$recall    , CM_nb$recall    , CM_oR$recall)
  F1_score  <- c(CM_svm$F1       , CM_id3$F1, 
                 CM_c45$F1       , CM_mrl$F1       , 
                 CM_rf$F1        , CM_nb$F1        , CM_oR$F1)
  result    <- data.frame(Model, Akurasi, Class, 
                          Presisi, Recall, F1_score)
  View(result)
```

